services:
  - type: web
    name: contracks
    env: python
    plan: free
    region: oregon
    buildCommand: ./build_and_copy.sh
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000